/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.tinder.jooq.tables.records


import com.pl.sggw.tinder.jooq.tables.TinderUser

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TinderUserRecord() : UpdatableRecordImpl<TinderUserRecord>(TinderUser.TINDER_USER), Record6<Long?, String?, String?, String?, LocalDateTime?, LocalDateTime?> {

    var id: Long?
        set(value) = set(0, value)
        get() = get(0) as Long?

    var userName: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var password: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var userEmail: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    var creationTimestamp: LocalDateTime?
        set(value) = set(4, value)
        get() = get(4) as LocalDateTime?

    var modificationTimestamp: LocalDateTime?
        set(value) = set(5, value)
        get() = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<Long?, String?, String?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row6<Long?, String?, String?, String?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row6<Long?, String?, String?, String?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row6<Long?, String?, String?, String?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<Long?> = TinderUser.TINDER_USER.ID
    override fun field2(): Field<String?> = TinderUser.TINDER_USER.USER_NAME
    override fun field3(): Field<String?> = TinderUser.TINDER_USER.PASSWORD
    override fun field4(): Field<String?> = TinderUser.TINDER_USER.USER_EMAIL
    override fun field5(): Field<LocalDateTime?> = TinderUser.TINDER_USER.CREATION_TIMESTAMP
    override fun field6(): Field<LocalDateTime?> = TinderUser.TINDER_USER.MODIFICATION_TIMESTAMP
    override fun component1(): Long? = id
    override fun component2(): String? = userName
    override fun component3(): String? = password
    override fun component4(): String? = userEmail
    override fun component5(): LocalDateTime? = creationTimestamp
    override fun component6(): LocalDateTime? = modificationTimestamp
    override fun value1(): Long? = id
    override fun value2(): String? = userName
    override fun value3(): String? = password
    override fun value4(): String? = userEmail
    override fun value5(): LocalDateTime? = creationTimestamp
    override fun value6(): LocalDateTime? = modificationTimestamp

    override fun value1(value: Long?): TinderUserRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): TinderUserRecord {
        this.userName = value
        return this
    }

    override fun value3(value: String?): TinderUserRecord {
        this.password = value
        return this
    }

    override fun value4(value: String?): TinderUserRecord {
        this.userEmail = value
        return this
    }

    override fun value5(value: LocalDateTime?): TinderUserRecord {
        this.creationTimestamp = value
        return this
    }

    override fun value6(value: LocalDateTime?): TinderUserRecord {
        this.modificationTimestamp = value
        return this
    }

    override fun values(value1: Long?, value2: String?, value3: String?, value4: String?, value5: LocalDateTime?, value6: LocalDateTime?): TinderUserRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised TinderUserRecord
     */
    constructor(id: Long? = null, userName: String? = null, password: String? = null, userEmail: String? = null, creationTimestamp: LocalDateTime? = null, modificationTimestamp: LocalDateTime? = null): this() {
        this.id = id
        this.userName = userName
        this.password = password
        this.userEmail = userEmail
        this.creationTimestamp = creationTimestamp
        this.modificationTimestamp = modificationTimestamp
    }
}
