/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.tinder.jooq.tables


import com.pl.sggw.tinder.jooq.Public
import com.pl.sggw.tinder.jooq.keys.USER_INFORMATION_USER_ID_KEY
import com.pl.sggw.tinder.jooq.tables.records.UserInformationRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserInformation(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UserInformationRecord>?,
    aliased: Table<UserInformationRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UserInformationRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.user_information</code>
         */
        val USER_INFORMATION = UserInformation()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserInformationRecord> = UserInformationRecord::class.java

    /**
     * The column <code>public.user_information.user_id</code>.
     */
    val USER_ID: TableField<UserInformationRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.user_information.description</code>.
     */
    val DESCRIPTION: TableField<UserInformationRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.user_information.phone_number</code>.
     */
    val PHONE_NUMBER: TableField<UserInformationRecord, String?> = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(9), this, "")

    /**
     * The column <code>public.user_information.photo</code>.
     */
    val PHOTO: TableField<UserInformationRecord, ByteArray?> = createField(DSL.name("photo"), SQLDataType.BLOB, this, "")

    /**
     * The column <code>public.user_information.creation_timestamp</code>.
     */
    val CREATION_TIMESTAMP: TableField<UserInformationRecord, LocalDateTime?> = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.user_information.modification_timestamp</code>.
     */
    val MODIFICATION_TIMESTAMP: TableField<UserInformationRecord, LocalDateTime?> = createField(DSL.name("modification_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserInformationRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UserInformationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.user_information</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.user_information</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.user_information</code> table reference
     */
    constructor(): this(DSL.name("user_information"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UserInformationRecord>): this(Internal.createPathAlias(child, key), child, key, USER_INFORMATION, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getKeys(): List<UniqueKey<UserInformationRecord>> = listOf(USER_INFORMATION_USER_ID_KEY)
    override fun `as`(alias: String): UserInformation = UserInformation(DSL.name(alias), this)
    override fun `as`(alias: Name): UserInformation = UserInformation(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserInformation = UserInformation(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserInformation = UserInformation(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Long?, String?, String?, ByteArray?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row6<Long?, String?, String?, ByteArray?, LocalDateTime?, LocalDateTime?>
}
