/*
 * This file is generated by jOOQ.
 */
package com.pl.sggw.tinder.jooq.tables.references


import com.pl.sggw.tinder.jooq.tables.TinderUser
import com.pl.sggw.tinder.jooq.tables.UserInformation
import com.pl.sggw.tinder.jooq.tables.UserMatchDecition



/**
 * The table <code>public.tinder_user</code>.
 */
val TINDER_USER = TinderUser.TINDER_USER

/**
 * The table <code>public.user_information</code>.
 */
val USER_INFORMATION = UserInformation.USER_INFORMATION

/**
 * The table <code>public.user_match_decition</code>.
 */
val USER_MATCH_DECITION = UserMatchDecition.USER_MATCH_DECITION
